#!/bin/bash

echo "Creating Guest User: $MYSQL_GUEST_USER"

mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<-EOSQL
  CREATE USER IF NOT EXISTS '$MYSQL_GUEST_USER'@'%' IDENTIFIED BY '$MYSQL_GUEST_PASSWORD';
  GRANT SELECT ON $MYSQL_DATABASE.* TO '$MYSQL_GUEST_USER'@'%';
  FLUSH PRIVILEGES;
EOSQL